# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 969)
        MainWindow.setMinimumSize(QtCore.QSize(960, 969))
        MainWindow.setMaximumSize(QtCore.QSize(960, 969))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(40, 90, 881, 111))
        self.groupBox_1.setObjectName("groupBox_1")
        self.pbURL_1 = QtWidgets.QPushButton(self.groupBox_1)
        self.pbURL_1.setGeometry(QtCore.QRect(780, 20, 91, 41))
        self.pbURL_1.setObjectName("pbURL_1")
        self.URL_string = QtWidgets.QLineEdit(self.groupBox_1)
        self.URL_string.setGeometry(QtCore.QRect(10, 20, 761, 41))
        self.URL_string.setObjectName("URL_string")
        self.label_3 = QtWidgets.QLabel(self.groupBox_1)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.label_3.setObjectName("label_3")
        self.Error_string = QtWidgets.QLineEdit(self.groupBox_1)
        self.Error_string.setGeometry(QtCore.QRect(90, 70, 681, 31))
        self.Error_string.setObjectName("Error_string")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 210, 881, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 431, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 431, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 91, 31))
        self.label_4.setObjectName("label_4")
        self.Time_work = QtWidgets.QLineEdit(self.groupBox_2)
        self.Time_work.setGeometry(QtCore.QRect(90, 300, 351, 31))
        self.Time_work.setObjectName("Time_work")
        self.Print_Requests = QtWidgets.QTextEdit(self.groupBox_2)
        self.Print_Requests.setGeometry(QtCore.QRect(10, 50, 431, 241))
        self.Print_Requests.setObjectName("Print_Requests")
        self.PrintHTTP = QtWidgets.QTextEdit(self.groupBox_2)
        self.PrintHTTP.setGeometry(QtCore.QRect(440, 50, 431, 241))
        self.PrintHTTP.setObjectName("PrintHTTP")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 560, 881, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pbSucces_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbSucces_2.setGeometry(QtCore.QRect(780, 20, 91, 41))
        self.pbSucces_2.setObjectName("pbSucces_2")
        self.Print_SuccesRequest = QtWidgets.QTextEdit(self.groupBox_3)
        self.Print_SuccesRequest.setGeometry(QtCore.QRect(10, 20, 761, 111))
        self.Print_SuccesRequest.setObjectName("Print_SuccesRequest")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 700, 881, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pbSite_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pbSite_3.setGeometry(QtCore.QRect(780, 20, 91, 41))
        self.pbSite_3.setObjectName("pbSite_3")
        self.Search_Site = QtWidgets.QTextEdit(self.groupBox_4)
        self.Search_Site.setGeometry(QtCore.QRect(10, 20, 761, 111))
        self.Search_Site.setObjectName("Search_Site")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.label_5.setObjectName("label_5")
        self.Time_work_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.Time_work_2.setGeometry(QtCore.QRect(90, 180, 351, 31))
        self.Time_work_2.setObjectName("Time_work_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.label_6.setObjectName("label_6")
        self.Error_string_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.Error_string_2.setGeometry(QtCore.QRect(90, 140, 681, 31))
        self.Error_string_2.setObjectName("Error_string_2")
        self.label_for_image = QtWidgets.QLabel(self.centralwidget)
        self.label_for_image.setGeometry(QtCore.QRect(370, 10, 341, 71))
        self.label_for_image.setText("")
        self.label_for_image.setObjectName("label_for_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "URL сайта"))
        self.pbURL_1.setText(_translate("MainWindow", "Поиск"))
        self.label_3.setText(_translate("MainWindow", "Вывод ошибки:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выполнение запроса"))
        self.label.setText(_translate("MainWindow", "Вывод запросов"))
        self.label_2.setText(_translate("MainWindow", "Код состояния HTTP"))
        self.label_4.setText(_translate("MainWindow", "Время работы:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Вывод успешных запросов "))
        self.pbSucces_2.setText(_translate("MainWindow", "Вывести"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Вывод запросов на сайте "))
        self.pbSite_3.setText(_translate("MainWindow", "Вывести"))
        self.label_5.setText(_translate("MainWindow", "Время работы:"))
        self.label_6.setText(_translate("MainWindow", "Результат:"))
